import {tx,a} from './page-sections.mjs';
import {icon} from '../dist/icons.js';
import {boardGuides} from '../dist/board-guides.js';

export function boardOverview(){
 return `<section class="wrap board-overview" id="board-overview" aria-label="Board selection guide">${Object.entries(boardGuides).map(([id,guide])=>`<div data-board-overview="${id}" ${id==='ndr'?'hidden':''}><div class="guide-heading"><p class="eyebrow">${tx(guide.status.th,guide.status.en)}</p>${tx(guide.audience.th,guide.audience.en,'h2')}</div><div class="guide-grid">${guide.sections.map(section=>`<article>${icon(section.icon)}${tx(section.title.th,section.title.en,'h3')}<ul>${section.items.map(item=>`<li>${tx(item.th,item.en)}</li>`).join('')}</ul></article>`).join('')}</div>${tx(guide.note.th,guide.note.en,'p','class="guide-note"')}</div>`).join('')}</section>`;
}

export function unifiedExplorer(){
 return `<section class="wrap model-section unified-explorer" id="hardware" aria-labelledby="model-title"><span id="explore-3d" class="anchor-alias"></span>
 <div class="model-heading"><div><p class="eyebrow">01 / ONE BOARD. EVERY ANGLE.</p>${tx('รู้จักบอร์ด ในมุมที่คุณเลือก','Meet the board. Choose your view.','h2','id="model-title"')}</div></div>
 <div class="model-shell"><div class="explorer-toolbar"><div class="board-switch" role="group" aria-label="Select board"><button type="button" data-board="training" aria-pressed="true">QWA309</button><button type="button" data-board="ndr" aria-pressed="false">TSOM / NDR</button></div><div class="view-switch" role="group" aria-label="Board view"><button type="button" data-view="photo" aria-pressed="true" aria-controls="board-stage">${icon('camera')}<span id="photo-view-label">Photo</span></button><button type="button" id="model-load" data-view="3d" aria-pressed="false" aria-controls="model-canvas">${icon('expand')}<span id="model-view-label">3D</span></button></div></div>
 <div class="explorer-layout"><div class="explorer-visual"><div class="model-stage" id="model-stage"><div class="board-stage" id="board-stage" data-board="training"><img id="model-poster" src="assets/training-board.webp" width="1000" height="750" alt="QWA309 Training assembly"></div><div id="model-canvas" hidden></div><div id="model-hotspots" class="model-hotspots" hidden></div><span class="model-kind" id="model-kind"></span></div>
 <div class="model-tools" id="model-tools" hidden><div class="model-key-controls" role="group" aria-label="3D controls"><button type="button" data-model-action="left" data-th-aria-label="หมุนซ้าย" data-en-aria-label="Rotate left" aria-label="Rotate left">↶</button><button type="button" data-model-action="right" data-th-aria-label="หมุนขวา" data-en-aria-label="Rotate right" aria-label="Rotate right">↷</button><button type="button" data-model-action="in" data-th-aria-label="ซูมเข้า" data-en-aria-label="Zoom in" aria-label="Zoom in">+</button><button type="button" data-model-action="out" data-th-aria-label="ซูมออก" data-en-aria-label="Zoom out" aria-label="Zoom out">−</button><button type="button" data-model-action="reset">${tx('มุมเริ่มต้น','Reset view')}</button></div><button type="button" id="model-explode" aria-pressed="false" hidden>${tx('แยกชั้น SOM / Base','Separate SOM / Base')}</button></div>
 <div class="model-caption"><p id="model-status" role="status"></p><button type="button" id="model-retry" hidden>${tx('ลองโหลด 3D อีกครั้ง','Retry 3D')}</button></div><p id="board-caption" class="explorer-caption"></p></div>
 <aside class="explorer-detail"><div class="feature-navigation"><button type="button" id="hotspot-prev" aria-label="Previous feature">←</button><span id="hotspot-count"></span><button type="button" id="hotspot-next" aria-label="Next feature">→</button></div><div id="hotspot-detail" class="hotspot-detail" aria-live="polite" aria-atomic="true"></div><div id="model-photo-note" hidden>${tx('โมดูลเสริมนี้มีในภาพถ่าย แต่ไม่มีในไฟล์ 3D ต้นทาง','This optional module is pictured but absent from the source 3D model.','p')}<button type="button" id="model-static">${tx('ดูจุดนี้ในภาพถ่าย','See this point in Photo')}</button></div><div class="model-parts" id="model-parts" role="group" aria-label="Hardware features"></div></aside></div></div>
 <p id="model-disclaimer" class="model-disclaimer"></p><noscript>${tx('เปิด JavaScript เพื่อสลับมุมมองและอ่าน Hotspot หรือดูเอกสารต้นทาง','Enable JavaScript to switch views and explore hotspots, or read the source docs.')} ${a('https://tesaiot.github.io/tesaiot-pse84-devkit-sdk/','เปิด SDK','Open SDK')}</noscript></section>`;
}
