import {writeFile,readFile} from 'node:fs/promises';
import {tx,a,sectionHead,photo,home,examples,sources} from './page-sections.mjs';
import {icon} from '../dist/icons.js';
import {escapeHTML as e} from '../dist/catalog.js';

const section=id=>{const found=[...home.matchAll(/<section\b[\s\S]*?<\/section>/g)].find(([s])=>s.includes(`id="${id}"`));if(!found)throw Error(`Missing section ${id}`);return found[0];};
const catalog=JSON.parse(await readFile(new URL('../dist/data/catalog.json',import.meta.url),'utf8'));
const items=catalog.examples;
const sensor=items.find(x=>x.id==='sensorhub');
const refs=[
 {id:'audio',icon:'audio',label:'AUDIO INTELLIGENCE',th:'ให้เสียงมีความหมาย',en:'Give sound meaning.',descTh:'เริ่มสำรวจ Audio classification ด้วยตัวอย่าง Baby Cry จาก Infineon ไม่ใช่เพียงการวัดระดับเสียง',descEn:'Explore audio classification with Infineon’s baby-cry starter example, beyond a sound-level meter.',hardware:'PDM / PCM · KIT_PSE84_AI',repo:'mtb-example-psoc-edge-ml-deepcraft-deploy-audio',shotTh:'ถ่ายเสียงทดสอบ → หน้าจอ Class / Confidence พร้อมระบุ Model และเงื่อนไขทดสอบ',shotEn:'Capture test audio → class / confidence on screen. Identify the model and test conditions.'},
 {id:'motion',icon:'sensor',label:'MOTION INTELLIGENCE',th:'จากการเคลื่อนไหว สู่กิจกรรม',en:'From motion to activity.',descTh:'ตัวอย่าง Human Activity Recognition ใช้ข้อมูล BMI270 เป็นจุดเริ่มต้น แยกจาก Example ที่แสดงกราฟ IMU',descEn:'Start from the BMI270 human-activity-recognition reference. This is separate from an IMU chart example.',hardware:'BMI270 · KIT_PSE84_AI',repo:'mtb-example-psoc-edge-ml-deepcraft-deploy-motion',shotTh:'ถ่ายการเคลื่อนไหวและ Class ที่ Model ทำนาย โดยให้เห็นบอร์ดและผลลัพธ์ในเฟรมเดียว',shotEn:'Show the movement, board and predicted activity together in one frame.'},
 {id:'vision',icon:'camera',label:'VISION INTELLIGENCE',th:'ให้บอร์ดมองเห็นไอเดีย',en:'Let your board see.',descTh:'ตัวอย่าง Rock–Paper–Scissors ใช้ USB Camera และแสดงผลบนจอ ต้องตรวจรุ่นกล้อง, USB Host, Power และ BSP ก่อนทดลอง',descEn:'Explore rock–paper–scissors detection with a USB camera and display. Check the camera, USB host, power and BSP first.',hardware:'USB Camera + LCD · KIT_PSE84_AI',repo:'mtb-example-psoc-edge-ml-deepcraft-deploy-vision',shotTh:'ถ่ายมือเป่ายิ้งฉุบ กล้อง USB ที่ต่ออยู่ และผล Detection บนจอ พร้อมแจ้งรุ่นกล้อง',shotEn:'Show the hand gesture, connected USB camera and detection result. Identify the camera model.'}
].map(r=>({...r,url:`https://github.com/Infineon/${r.repo}`,status:'upstream-reference',tesaValidation:'pending'}));
await writeFile(new URL('../dist/data/ai-references.json',import.meta.url),JSON.stringify({reviewed:'2026-09-21',scope:'Official upstream references; not validated on the TESA assemblies by this PoC.',references:refs},null,2)+'\n');

function shell(page,th,en,content){
 const hub=['examples','featured','edge-ai'].includes(page);
 return `<!doctype html>
<html lang="th" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="description" content="Discover TESAIoT hardware, source-led projects and Edge AI pathways. Independent design PoC; board compatibility is stated separately."><title data-th="${e(th)}" data-en="${e(en)}">${e(th)}</title><link rel="icon" href="favicon.svg"><script src="preferences.js"></script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="v2.css"><link rel="stylesheet" href="v3.css"></head>
<body data-page="${page}"><a class="skip" href="#main">${tx('ข้ามไปเนื้อหา','Skip to content')}</a><div class="poc-bar wrap"><span><i class="status-dot"></i> TESA<strong>IoT</strong> / DESIGN EXPLORATION 03</span>${tx('PoC · ไม่ใช่เว็บไซต์ทางการ · ไม่เชื่อมต่อ Hardware','PoC · Unofficial · No hardware connection')}</div>
<header class="header"><div class="wrap header-inner"><a class="brand" href="index.html" aria-label="TESAIoT Board Explorer home"><span class="brand-mark">${icon('chip')}</span><span><b>TESA<span>IoT</span></b><small>IDEAS INTO HARDWARE</small></span></a><nav aria-label="Main navigation">${a('index.html#boards','บอร์ด','Boards',['index','boards'].includes(page)?'nav-link active':'nav-link')}${a('examples.html','Project Hub','Project Hub',hub?'nav-link active':'nav-link')}${a('learn.html','เริ่มต้น / Docs','Learn / Docs',page==='learn'?'nav-link active':'nav-link')}</nav><div class="preferences"><div class="language-switch" role="group" aria-label="Language"><button type="button" data-lang="th" aria-pressed="true">TH</button><button type="button" data-lang="en" aria-pressed="false">EN</button></div><button type="button" class="theme-toggle" id="theme-toggle" aria-label="Switch color theme">${icon('moon')}</button></div></div></header>
<main id="main">${content}</main>
<footer class="footer wrap"><div><a class="footer-brand" href="index.html">TESAIoT / IDEAS INTO HARDWARE</a>${tx('เลือกไอเดีย รู้จักบอร์ด แล้วสร้างสิ่งที่เป็นของคุณ','Find an idea. Meet the hardware. Make it yours.','p')}${tx('Independent Design PoC · ไม่ใช่เว็บไซต์ทางการของ TESA','Independent design PoC · Not the official TESA website','small')}</div><div><a href="sources.html">${tx('แหล่งข้อมูลและขอบเขต','Sources & scope')}</a><a href="https://github.com/nitikorn20/tesaiot-board-explorer-poc" target="_blank" rel="noopener noreferrer">PoC GitHub ↗</a><p>Built with <a href="https://github.com/tesaiot/developer-hub">TESAIoT Platform Examples</a><br>© 2025 TESAIoT Platform by TESA</p></div></footer><script type="module" src="ui.js"></script><script type="module" src="explorer.js"></script></body></html>`;
}
const collectionNav=active=>`<nav class="collection-nav wrap" aria-label="Project collections">${[['examples','โปรเจกต์ทั้งหมด','All projects'],['featured','Featured','Featured'],['edge-ai','Edge AI Hub','Edge AI Hub']].map(([id,th,en])=>`<a href="${id}.html" ${active===id?'aria-current="page"':''}>${tx(th,en)}${id==='edge-ai'?icon('chip'):''}</a>`).join('')}</nav>`;
const masthead=(label,th,en,subTh,subEn)=>`<section class="page-masthead wrap"><p class="eyebrow">${label}</p>${tx(th,en,'h1')}${tx(subTh,subEn,'p','class="lead"')}</section>`;
const poster=`<img src="assets/bento-edge-ai-poster.jpg" alt="BENTO Edge AI demo running on a Training assembly LCD" width="960" height="632">`;
const storyCards=()=>`<div class="story-grid">
<article class="story-card"><a href="boards.html?board=training#playground" class="story-image rgb-art" aria-label="Pot to RGB browser simulation"><span class="demo-matrix" aria-hidden="true">${Array.from({length:32},(_,i)=>`<i style="--delay:${i%8}"></i>`).join('')}</span><span class="media-tag">BROWSER SIMULATION</span></a><div class="story-copy"><p class="eyebrow">01 / INPUT → OUTPUT</p>${tx('หมุนหนึ่งครั้ง เห็นไอเดียเป็นสี','A small turn. A bright idea.','h3')}${tx('ลอง Pot → RGB บนหน้าเว็บ แล้วเปิด Source สำหรับ Hardware จริง การเลือกสีด้วย Threshold ไม่ใช่ AI','Try Pot → RGB in the browser, then explore its hardware source. Threshold-based color selection, not AI.','p')}${a('examples.html#rgb','เปิด Hardware Example','Open hardware example')}</div></article>
<article class="story-card"><a href="examples.html#sensorhub" class="story-image" aria-label="Sensor Hub example"><img src="${e(sensor.image)}" alt="${e(sensor.subtitle)} — original source screenshot" width="800" height="480" loading="lazy"><span class="media-tag">SOURCE SCREENSHOT</span></a><div class="story-copy"><p class="eyebrow">02 / SENSE → UNDERSTAND</p>${tx('ข้อมูลรอบตัว บนจอเดียว','Your environment. One display.','h3')}${tx('เริ่มอ่าน Sensor และรวมข้อมูลเป็น Dashboard เพื่อเข้าใจ Input ก่อนต่อยอด Application','Explore sensors together in a dashboard. Understand the inputs before building an application.','p')}${a('examples.html#sensorhub','สำรวจ Sensor Hub','Explore Sensor Hub')}</div></article>
<article class="story-card"><a href="edge-ai.html#demo" class="story-image" aria-label="Watch existing BENTO Edge AI demo">${poster}<span class="play-circle" aria-hidden="true">▶</span><span class="media-tag">EXISTING DEMO · 0:39</span></a><div class="story-copy"><p class="eyebrow">03 / SIGNAL → INTELLIGENCE</p>${tx('เมื่อบอร์ดเริ่มตีความสัญญาณ','When signals become meaning.','h3')}${tx('ดูคลิป BENTO ต้นทาง แล้วเลือกเส้นทาง Audio, Motion หรือ Vision จาก Reference ของ Infineon','Watch the source BENTO demo, then explore Infineon audio, motion and vision references.','p')}${a('edge-ai.html','เข้าสู่ Edge AI Hub','Enter Edge AI Hub')}</div></article></div>`;
const workflow=()=>`<div class="workflow"><article><span class="step-no">01</span>${icon('search')}${tx('เลือก Model ที่มีอยู่','Find an existing model','h3')}${tx('สำรวจ Model และ Solution พร้อมตรวจ Target และเงื่อนไขการใช้','Explore models and solutions. Check target support and usage terms.','p')}${a('https://deepcraft.infineon.com/','DEEPCRAFT AI Hub','DEEPCRAFT AI Hub')}</article><article><span class="step-no">02</span>${icon('sensor')}${tx('สร้าง Model ของคุณ','Create your own model','h3')}${tx('รวบรวมข้อมูล Label, Train และเตรียม Code สำหรับงานที่ต้องการ','Collect and label data, train, and generate code for your use case.','p')}${a('https://www.infineon.com/design-resources/embedded-software/deepcraft-edge-ai-solutions','รู้จัก DEEPCRAFT Studio','Explore DEEPCRAFT Studio')}</article><article><span class="step-no">03</span>${icon('chip')}${tx('นำ Model มาสู่ Device','Bring a model to the device','h3')}${tx('มี Model แล้ว? สำรวจ Model Converter และตรวจ Operator, Memory และ Target','Already have a model? Explore Model Converter; check operators, memory and target support.','p')}${a('https://www.infineon.com/design-resources/embedded-software/deepcraft-edge-ai-solutions','รู้จัก Model Converter','Explore Model Converter')}</article></div>`;

const lineup=section('boards').replace(/<button type="button" class="text-link" data-explore-board="(training|ndr)">([\s\S]*?)<\/button>/g,(_,id,body)=>`<a class="text-link" href="boards.html?board=${id}">${body}</a>`);
const homePage=`<section class="editorial-hero wrap"><div class="editorial-copy"><p class="eyebrow">BUILD SOMETHING THAT RESPONDS.</p><h1>${tx('ไอเดียของคุณ','Your next idea.')}<br>${tx('เริ่มมีชีวิตที่นี่','Starts here.','em')}</h1>${tx('บอร์ดที่ทำให้คุณลองหมุน สัมผัส ฟัง และมองเห็น — จากผลลัพธ์แรกบนหน้าจอ สู่ Application และ Edge AI ที่คุณสร้างต่อได้','Turn. Touch. Listen. See. Start with a visible result, then explore applications and Edge AI you can make your own.','p','class="lead"')}<div class="actions">${a('#boards','เลือกบอร์ดที่ใช่','Find your board','button primary')}${a('examples.html','หาไอเดียเริ่มต้น','Find your first project','button secondary')}</div><div class="hero-note">${icon('code')}${tx('Hardware จริง · Source ที่เปิดดูได้ · เส้นทางเรียนรู้ที่ชัดเจน','Real hardware · Explore the source · Find your next step')}</div></div><a class="hero-film" href="edge-ai.html#demo" aria-label="Watch existing BENTO Edge AI demonstration"><div class="film-top"><span>ON THE BOARD / 001</span><span>EXISTING BENTO DEMO</span></div>${poster}<div class="film-caption"><span class="play-circle" aria-hidden="true">▶</span><div><span class="eyebrow">TRAINING SERIES / EDGE AI</span>${tx('เห็นการทำงาน ก่อนเริ่มสร้าง','See it work. Then start building.','h2')}</div><span class="film-time">0:39 ↗</span></div></a></section>
<div class="editorial-strip wrap"><span>02 <small>${tx('เส้นทางบอร์ด','board paths')}</small></span><span>09 <small>${tx('Hardware Examples','hardware examples')}</small></span><span>03 <small>${tx('AI References จาก Infineon','Infineon AI references')}</small></span><a href="sources.html">${tx('ตรวจต้นทางและสถานะ','See sources & status')} ↗</a></div>
${lineup}
<section class="section wrap interests">${sectionHead('START WITH A POSSIBILITY','คุณอยากให้บอร์ดทำอะไร?','What do you want to make?','เลือกจากผลลัพธ์ที่สนใจ แล้วค่อยดู Hardware และ Requirements','Choose an outcome, then explore the hardware and requirements.')}<div class="interest-grid">${[['sliders','Control & HMI','หมุน แตะ แล้วเห็นผล','Turn, touch, see a result','examples.html?category=control'],['sensor','Sensing & Motion','อ่านโลกจริงให้เป็นข้อมูล','Turn the physical world into data','examples.html?category=sensors'],['audio','Audio Intelligence','จากเสียง สู่การจำแนก','From sound to classification','edge-ai.html#audio'],['camera','Vision AI','ทดลองมองเห็นด้วย USB Camera','Explore vision with a USB camera','edge-ai.html#vision']].map(([i,title,th,en,url])=>`<a href="${url}" class="interest-card">${icon(i)}<h3>${title}</h3>${tx(th,en,'p')}<span class="interest-arrow">↗</span></a>`).join('')}</div></section>
<section class="section wrap">${sectionHead('FEATURED / EDITOR’S SELECTION','สามไอเดีย เพื่อก้าวแรกของคุณ','Three ideas. Your first spark.','คัดจาก Hardware Example, Browser Simulation และ Demo ต้นทาง','A curated mix of hardware examples, browser interaction and source footage.')}${storyCards()}<div class="section-bottom">${a('featured.html','ดู Featured Collection','Explore the Featured collection','button secondary')}</div></section>
<section class="ai-banner"><div class="wrap"><div><p class="eyebrow">PSOC™ EDGE E84 / DEEPCRAFT™</p>${tx('จากการอ่าน Sensor','From sensing the world.','h2')}${tx('สู่การเข้าใจสัญญาณ','To making sense of it.','h2','class="accent-line"')}${tx('สำรวจเส้นทาง Model → Firmware → Board ผ่านเครื่องมือของ Infineon โดยแยก Target Support และผลทดสอบของแต่ละบอร์ด','Explore the model → firmware → board journey with Infineon tools. Target support and board validation remain separate checks.','p')}${a('edge-ai.html','สำรวจ Edge AI Hub','Explore Edge AI Hub','button primary')}</div><div class="signal-flow" aria-label="Conceptual Edge AI workflow"><span>${icon('sensor')} INPUT</span><b>→</b><span>${icon('chip')} MODEL</span><b>→</b><span>${icon('display')} ACTION</span><small>CONCEPTUAL WORKFLOW / NOT LIVE INFERENCE</small></div></div></section>
<section class="section wrap" id="start">${sectionHead('READY FOR YOUR FIRST BUILD?','เปิด Source แล้วเริ่มก้าวต่อไป','Your next step starts with source.','ตรวจบอร์ด เลือกตัวอย่าง แล้วตั้งค่า SDK จากเอกสารต้นทาง','Check your board, pick an example, and follow the upstream SDK documentation.')}${a('learn.html','เริ่มต้นและดู Docs','Get started & open docs','button primary')}</section>`;

const firstSection=section('hardware');
const tour=firstSection.slice(firstSection.indexOf('<div class="tour-shell">'),firstSection.lastIndexOf('</section>'));
const boardPage=`<section class="board-detail-intro wrap"><a class="text-link" href="index.html#boards">← ${tx('กลับไปเลือกบอร์ด','All boards')}</a><p class="eyebrow">HARDWARE / INTERACTIVE EXPLORER</p><h1 id="board-page-title">QWA309 Training Kit</h1><p id="board-page-summary" class="lead"></p><div class="detail-jumps">${a('#hardware','Hardware Tour','Hardware tour')}${a('#architecture','Block Diagram','Block diagram')}${a('examples.html','ค้นหา Examples','Browse examples')}</div></section><section class="board-tour-layout wrap" id="hardware"><div class="tour-intro"><span class="section-index">01</span>${tx('รู้จักทุกจุด','Meet every connection.','h2')}${tx('เลื่อนเมาส์ แตะ หรือใช้คีย์บอร์ดที่หมายเลข เพื่อดูว่าแต่ละส่วนทำอะไรได้','Hover, tap or focus a numbered point to discover what each part does.','p')}<div class="tour-legend"><span>${icon('board')} ${tx('ภาพบอร์ดและ Reference','Board image & reference')}</span><span>${icon('code')} ${tx('ไม่มีการเชื่อมต่อ Hardware','No hardware connection')}</span></div></div>${tour}</section>${section('architecture')}${section('playground').replace('id="playground"','id="playground" data-training-only')}<section class="wrap section board-next"><p class="eyebrow">KNOW THE BOARD. FIND YOUR NEXT STEP.</p>${tx('พร้อมสำรวจสิ่งที่จะสร้างต่อ?','Ready to explore what comes next?','h2')}<div class="actions">${a('examples.html','เปิด Project Hub','Open Project Hub','button primary')}${a('edge-ai.html','สำรวจ Edge AI','Explore Edge AI','button secondary')}${a('learn.html','SDK และการเตรียมบอร์ด','SDK & board setup')}</div></section>`;
const projectPage=`${collectionNav('examples')}${masthead('PROJECT HUB / CURATED HARDWARE COLLECTION','เริ่มจากสิ่งที่อยากสร้าง','Start with what you want to make.','สำรวจ 9 Hardware Examples พร้อมอุปกรณ์ที่ใช้ ภาพต้นทาง และ Source สำหรับก้าวต่อไป','Explore nine hardware examples with requirements, source images and code for your next step.')}<div class="hub-note wrap">${icon('chip')}${tx('มองหา Machine Learning? แยก Audio / Motion / Vision References ไว้ใน Edge AI Hub','Looking for machine learning? Audio, motion and vision references have their own Edge AI Hub.')}${a('edge-ai.html','ดู AI References','Explore AI references')}</div>${examples.slice(examples.indexOf('<section class="catalog-section'))}`;
const featuredPage=`${collectionNav('featured')}${masthead('FEATURED / A CURATED STARTING POINT','ไอเดียเด่น ที่ชวนให้ลงมือ','Ideas worth a closer look.','เลือกสามเรื่องที่อธิบายสิ่งที่บอร์ดทำได้ ตั้งแต่ Input / Output จนถึงเส้นทาง Edge AI','Three stories connecting physical inputs, visible results and a path into Edge AI.')}<section class="wrap featured-collection">${storyCards()}</section><section class="wrap section"><div class="editorial-callout"><p class="eyebrow">CURATED, NOT RANKED</p>${tx('Featured คือเรื่องที่คัดมาเล่า','Featured means curated.','h2')}${tx('ไม่ใช่หมวด Hardware ไม่ใช่คะแนนนิยม และไม่ใช่ตรารับรอง Compatibility แต่ละเรื่องแสดงสถานะและทางไป Source ของตัวเอง','This is an editorial collection, not a hardware category, popularity ranking or compatibility certificate. Each story retains its own source and status.','p')}${a('examples.html','สำรวจ Hardware ทั้ง 9 Examples','Explore all nine hardware examples')}</div></section>`;
const aiCard=r=>`<article class="ai-reference" id="${r.id}"><div class="reference-visual ${r.id}">${icon(r.icon)}<span class="reference-track" aria-hidden="true"></span><span class="media-tag">${tx('CONCEPT · รอถ่าย Demo','CONCEPT · Demo footage needed')}</span></div><div class="reference-body"><p class="eyebrow">${r.label}</p>${tx(r.th,r.en,'h3')}${tx(r.descTh,r.descEn,'p')}<p class="hardware-line">${icon(r.icon)} ${r.hardware}</p><div class="reference-status"><span>UPSTREAM REFERENCE</span>${tx('TESA validation: รอตรวจสอบ','TESA validation: pending')}</div>${a(r.url,'อ่าน Infineon README','Read Infineon README')}<details class="shot-brief"><summary>${tx('ภาพที่ควรถ่ายมาแทน','What to film here')}</summary>${tx(r.shotTh,r.shotEn,'p')}</details></div></article>`;
const aiPage=`${collectionNav('edge-ai')}${masthead('EDGE AI HUB / PSOC™ EDGE E84','มากกว่ารับสัญญาณ คือเข้าใจมัน','Don’t just sense it. Make sense of it.','ดู Demo ต้นทาง เลือกไอเดีย แล้วสำรวจเครื่องมือและ Model ที่เหมาะกับ Hardware ของคุณ','Watch a source demo, choose a use case, and explore models and tools for your hardware.')}
<section class="demo-feature wrap" id="demo"><div class="demo-video"><video controls playsinline preload="none" poster="assets/bento-edge-ai-poster.jpg" width="960" height="632" aria-describedby="demo-description"><source src="assets/bento-edge-ai-demo.mp4" type="video/mp4"><track kind="descriptions" src="assets/bento-demo-en.vtt" srclang="en" label="Visual description (English)">${tx('Browser นี้ไม่รองรับวิดีโอ ใช้ลิงก์ MP4 ด้านล่าง','Your browser cannot play this video. Use the MP4 link below.')}</video><p class="video-credit">BENTO Demo — Edge AI (Multi-model) · ${tx('คลิปจาก Canva ต้นทาง หน้า 21','Source Canva slide 21')} · 0:39</p></div><div class="demo-copy"><span class="status">EXISTING HARDWARE DEMO</span>${tx('Edge AI บนหน้าจอบอร์ดจริง','Edge AI. On a real board.','h2')}${tx('คลิปต้นทางแสดงหน้าจอ BENTO Edge AI บนชุด Training สลับหน้า Motion Detection และ All Models พร้อมสถานะการทำงาน','The source clip shows the BENTO Edge AI interface on a Training assembly, including Motion Detection and All Models views with on-screen status.','p','id="demo-description"')}<p class="notice">${tx('Demo เดิม ไม่ใช่ผลทดสอบใหม่ของ PoC และไม่ยืนยัน NDR Base / ความแม่นยำของ Model ตัวเลขบนจอเป็นส่วนหนึ่งของคลิปต้นทาง','Existing demo, not a new PoC test, NDR-base validation or model-accuracy benchmark. On-screen values belong to the source footage.')}</p><details><summary>${tx('คำอธิบายวิดีโอและการตัดต่อ','Video description & edit notes')}</summary>${tx('เห็นบอร์ดจริงและมือแตะจอ เลือกหน้า Motion จากนั้นแสดง All Models และรายการเหตุการณ์ คลิปไม่มีเสียง ตัดเฉพาะพื้นที่วิดีโอออกจากสไลด์และย่อขนาด ไม่เร่งเวลา ไม่สร้างผลลัพธ์เพิ่ม','A hand operates the LCD on the board. The interface shows Motion, then All Models and event entries. This silent clip crops the video region out of the slide and resizes it. Playback speed and displayed results are unchanged.','p')}</details>${a('assets/bento-edge-ai-demo.mp4','เปิดไฟล์วิดีโอ','Open video file')}</div></section>
<section class="section wrap">${sectionHead('CHOOSE YOUR AI STARTING POINT','สามเส้นทางจาก Infineon','Three paths from Infineon.','ตัวอย่างต้นทางสำหรับ KIT_PSE84_AI ไม่ใช่ Firmware ที่ยืนยันบน TESA ทั้งสองบอร์ดแล้ว','Upstream KIT_PSE84_AI references, not firmware validated on both TESA assemblies.')}<div class="ai-reference-grid">${refs.map(aiCard).join('')}</div><p class="notice ai-boundary">${tx('PSoC Edge E84 เป็นตระกูลชิปร่วมกัน แต่ Training และ TSOM + NDR ใช้ Base / Interface / BSP ต่างกัน ต้องตรวจ Revision, Sensor, Memory, Power และ Model Support แยกกัน','A shared PSoC Edge E84 family does not mean identical carriers, interfaces or BSPs. Check revision, sensors, memory, power and model support separately for Training and TSOM + NDR.')}</p></section>
<section class="deepcraft-section"><div class="wrap">${sectionHead('NEXT / DEEPCRAFT™','เลือกเครื่องมือ ตามจุดที่คุณเริ่ม','Pick the path that fits your start.','ลิงก์ไปยังเครื่องมือของ Infineon โดยตรง ไม่มีการ Train หรือรัน Inference บนเว็บไซต์ PoC นี้','Direct links to Infineon tools. This PoC does not train models or perform inference.')}${workflow()}<p class="fineprint">${tx('ตรวจ Supported Target, Model License, Operator และเวอร์ชัน Toolchain ในเอกสารปัจจุบันก่อนใช้งาน ไม่ใช่ทุก Model จะพร้อมรันบนทุกบอร์ด','Check current target support, model licenses, operators and toolchain versions. Not every model runs on every board.')}</p></div></section><section class="wrap section">${a('learn.html','กลับไปเตรียม SDK และบอร์ด','Prepare your SDK & board','button primary')}</section>`;
const learnPage=`${masthead('LEARN / YOUR FIRST BUILD','ก้าวแรกที่ชัดเจน ก่อนเปิด IDE','A clear start. Before the IDE.','เริ่มจากบอร์ดและ Example ที่ตรงกัน แล้วตามไปยังเอกสารต้นทางที่ดูแลโดยเจ้าของโปรเจกต์','Match your board to an example, then continue with the documentation maintained by its owner.')}<section class="wrap learn-paths"><article><span class="section-index">01</span><h2>QWA309 Training</h2>${tx('ตรวจ Controller KIT_PSE84_AI, QWA309 Revision, อุปกรณ์เสริม และ Board ID ของ Example อย่าถือว่าทุก Example ใช้กับทุกชุดได้ทันที','Check KIT_PSE84_AI, the QWA309 revision, fitted peripherals and the example’s Board ID. Do not assume every example runs on every assembly.','p')}<ol><li>${tx('ดู Hardware Tour และรายการอุปกรณ์','Explore the hardware tour and fitted peripherals')}</li><li>${tx('เลือก Example และอ่าน Requirements / README','Choose an example and read its requirements / README')}</li><li>${tx('ติดตั้ง SDK / BSP ตามเอกสาร แล้ว Build และทดสอบบนบอร์ด','Follow upstream SDK / BSP setup, then build and test on the board')}</li></ol><div class="actions">${a('https://tesaiot.github.io/tesaiot-pse84-devkit-sdk/','เปิด Training SDK','Open Training SDK','button primary')}${a('examples.html?board=training','เลือก Example','Choose an example')}</div></article><article><span class="section-index">02</span><h2>TSOM + NDR Base</h2>${tx('เส้นทาง Preview ของแพลตฟอร์มใหม่ ยังไม่มี Example ที่รับรองสำหรับ Base ใหม่ใน PoC นี้ ผลบน carrier เดิมไม่ยืนยัน carrier ใหม่','A preview of the new platform. This PoC has no verified examples for the new base. Results on a previous carrier do not validate a new one.','p')}<ol><li>${tx('ยืนยัน Base Revision, Schematic, Power และ Pin Map','Confirm base revision, schematic, power and pin map')}</li><li>${tx('รับ BSP / Bring-up และขอบเขต Interface ที่พร้อมทดสอบ','Confirm BSP / bring-up handoff and testable interfaces')}</li><li>${tx('ทำ Validation ตามอุปกรณ์ แล้วจึงจัด Example + Media แยกบอร์ด','Validate each device, then publish board-specific examples and media')}</li></ol><div class="actions">${a('boards.html?board=ndr','ดู NDR Preview','Explore NDR preview','button secondary')}</div></article></section><section class="wrap section"><div class="editorial-callout"><p class="eyebrow">AFTER YOUR FIRST HARDWARE EXAMPLE</p>${tx('อยากไปต่อด้าน AI?','Ready to explore AI?','h2')}${tx('แยกการทดสอบ Sensor ออกจากการทดสอบ Model แล้วเลือก Audio, Motion หรือ Vision Reference ที่ตรงกับอุปกรณ์','Separate sensor validation from model validation. Choose an audio, motion or vision reference matched to the hardware.','p')}${a('edge-ai.html','เปิด Edge AI Hub','Open Edge AI Hub')}</div><p class="notice">${tx('PoC นี้ยังไม่มี Online Flash, Firmware Build หรือ Hardware Validation · ไม่แก้ระบบ dev.tesaiot.dev ที่ใช้งานอยู่','No online flash, firmware build or hardware validation is performed here. The existing dev.tesaiot.dev service is unchanged.')}</p></section>`;
const sourceAddition=`<section class="wrap source-v3 section"><p class="eyebrow">V3 / STORY, AI & MEDIA</p>${tx('ข้อมูลใหม่ในรอบนี้','New in this edition','h2')}<div class="scope-grid"><article><h3>BENTO Edge AI footage</h3>${tx('คลิปจาก Canva ที่ผู้ใช้ระบุ หน้า 21 Export เฉพาะหน้านั้น แล้วตัดเฉพาะบริเวณวิดีโอ ย่อเป็น 960 × 632 และตัดเสียง ระยะเวลา 39 วินาที Poster เป็นเฟรมที่ 15 วินาที ไม่เผยแพร่สไลด์เต็มหรือภาพประกอบด้านข้าง','From the user-supplied Canva slide 21. Only the video region is cropped, resized to 960 × 632, and made silent (39 seconds). Poster: frame at 15 seconds. No full slide or surrounding illustrations are published.','p')}${tx('สิทธิ์ยังเป็นของเจ้าของเดิม ไม่รวมใน Apache license ของโค้ดเว็บ และไม่ใช่ผล Validation ของ PoC','Rights remain with the original owners; excluded from the site code’s Apache license. Not PoC validation evidence.','p')}</article><article><h3>AI references & concepts</h3>${tx('Audio / Motion / Vision ใช้ README ทางการของ Infineon เป็นต้นทาง แยกจาก 9 Hardware Examples ภาพ Concept วาดด้วย CSS/Icon ไม่ใช่ผลทดสอบหรือภาพ Hardware ที่สร้างขึ้น','Audio / motion / vision link to official Infineon READMEs, separate from the nine hardware examples. CSS/icon concepts are not test results or generated hardware photos.','p')}${a('data/ai-references.json','ดู AI Reference Manifest','View AI reference manifest')}</article></div><div class="research-list"><article><h3>Arduino / Project Hub</h3>${tx('ใช้เป็นแรงบันดาลใจเรื่อง Product Story, หมวดโปรเจกต์ และ Editorial Collection ไม่คัดลอกแบรนด์ สื่อ หรือจำนวน Like','Inspired by product storytelling, project discovery and editorial collections. No copied branding, media or social counts.','p')}${a('https://www.arduino.cc/','Product reference','Product reference')}<br>${a('https://projecthub.arduino.cc/sections/featured','Featured reference','Featured reference')}<br>${a('https://projecthub.arduino.cc/sections/dragonwing-hub','Themed Hub reference','Themed Hub reference')}</article><article><h3>Infineon / DEEPCRAFT</h3>${tx('ตรวจต้นทาง 21 กันยายน 2026 · เนื้อหาของผู้ให้บริการอาจเปลี่ยน ตรวจ Requirements ปัจจุบันก่อนเริ่ม','Reviewed September 21, 2026. Vendor content may change; check current requirements before starting.','p')}${a('https://www.infineon.com/product-information/kit_pse84_ai','KIT_PSE84_AI','KIT_PSE84_AI')}<br>${a('https://www.infineon.com/design-resources/embedded-software/deepcraft-edge-ai-solutions','DEEPCRAFT tools','DEEPCRAFT tools')}</article></div></section>`;
const pages=[['index','TESAIoT · ไอเดียเริ่มที่บอร์ด','TESAIoT · Ideas into hardware',homePage],['boards','TESAIoT · สำรวจ Hardware','TESAIoT · Hardware explorer',boardPage],['examples','TESAIoT · Project Hub','TESAIoT · Project Hub',projectPage],['featured','TESAIoT · Featured','TESAIoT · Featured',featuredPage],['edge-ai','TESAIoT · Edge AI Hub','TESAIoT · Edge AI Hub',aiPage],['learn','TESAIoT · เริ่มต้นและ Docs','TESAIoT · Learn & docs',learnPage],['sources','TESAIoT · ต้นทางและขอบเขต','TESAIoT · Sources & scope',sourceAddition+sources]];
for(const [page,th,en,content] of pages){
  const withHeading=page==='sources'?masthead('SOURCES / SCOPE / PROVENANCE','รู้ต้นทาง ก่อนเริ่มต่อยอด','Know the source. Build with context.','แยกข้อมูลต้นทาง แนวคิดออกแบบ และสถานะการทดสอบให้ตรวจสอบได้','Distinguish source evidence, design concepts and validation status.')+content.replace('<h1>Sources & scope</h1>','<h2>Hardware & catalog sources</h2>'):content;
  // Prefer WebM for embedded browsers; retain MP4 for other clients and download.
  const rendered=withHeading.replace('<source src="assets/bento-edge-ai-demo.mp4"', '<source src="assets/bento-edge-ai-demo.webm" type="video/webm"><source src="assets/bento-edge-ai-demo.mp4"');
  await writeFile(new URL(`../dist/${page}.html`,import.meta.url),shell(page,th,en,rendered));
}
console.log(`Built ${pages.length} bilingual pages and ${refs.length} upstream AI references.`);
