import {tx,a,sectionHead,photo} from './page-sections.mjs';
import {icon} from '../dist/icons.js';
import {boardGuides} from '../dist/board-guides.js';

// Editorial homepage: one story, two products, one route into projects.
export function productHome(stories) {
 return `<section class="cinema-hero" aria-labelledby="hero-title">
 <video id="hero-video" muted loop playsinline preload="none" poster="assets/bento-edge-ai-poster.jpg" aria-hidden="true" data-webm="assets/tesa-hero.webm" data-mp4="assets/tesa-hero.mp4"></video>
 <div class="cinema-shade"></div>
 <div class="wrap cinema-copy"><p class="eyebrow">TESAIoT / IDEAS INTO HARDWARE</p><h1 id="hero-title">${tx('ให้ไอเดีย','Give your ideas')}<br>${tx('ตอบสนองโลกจริง','a real-world response.','em')}</h1>
 ${tx('เริ่มจากบอร์ด สร้างสิ่งที่มองเห็นได้ แล้วต่อยอดสู่ Edge AI','Start with a board. Make something tangible. Take your next step into Edge AI.','p','class="cinema-lead"')}
 <div class="actions">${a('#boards','เลือกบอร์ดของคุณ','Explore the boards','button primary')}${a('examples.html','ค้นหาโปรเจกต์','Find a project','button cinema-secondary')}</div></div>
 <div class="wrap cinema-bottom"><a href="edge-ai.html#demo" class="film-credit"><span class="film-dot"></span><span>BENTO / EDGE AI DEMO<small>${tx('คลิปจากชุด Training · ดู Demo เต็ม','Training assembly footage · Watch full demo')}</small></span>${icon('arrow')}</a><button id="hero-play" type="button" aria-pressed="false" class="media-control">${icon('play')}${tx('เล่นวิดีโอ','Play video','span','data-video-label')}</button></div>
 </section>
 <section class="product-triptych" id="boards" aria-label="Boards and developer tools">
 <article class="product-tile product-training"><div class="product-tile-heading"><p class="eyebrow">TRAINING SERIES</p><h2>QWA309 Training Kit</h2>${tx(boardGuides.training.audience.th,boardGuides.training.audience.en,'p')}</div><a class="product-media" href="boards.html?board=training" aria-label="Explore QWA309 Training Kit">${photo('training')}</a><div class="product-tile-bottom"><p class="product-caption">KIT_PSE84_AI + QWA309</p>${a('boards.html?board=training','สำรวจ Training Board','Explore Training Board','button product-button')}</div></article>
 <article class="product-tile product-ndr"><div class="product-tile-heading"><p class="eyebrow">DEVELOPMENT PREVIEW</p><h2>TSOM + NDR Base</h2>${tx(boardGuides.ndr.audience.th,boardGuides.ndr.audience.en,'p')}</div><a class="product-media" href="boards.html?board=ndr" aria-label="Explore NDR development concept"><img src="assets/ndr-concept.svg" alt="Concept illustration of a compute module and carrier, not the final NDR PCB" data-th-alt="ภาพจำลอง Compute Module กับ Base ไม่ใช่ PCB NDR ฉบับจริง" data-en-alt="Concept illustration of a compute module and carrier, not the final NDR PCB" width="600" height="400" loading="lazy"></a><div class="product-tile-bottom"><p class="product-caption">${tx('ภาพจำลอง · ไม่ใช่แบบ PCB สุดท้าย','CONCEPT · NOT FINAL PCB GEOMETRY')}</p>${a('boards.html?board=ndr','สำรวจ Development Preview','Explore Development Preview','button product-button')}</div></article>
 <article class="product-tile product-hub"><div class="product-tile-heading"><p class="eyebrow">DEVELOPER HUB</p><h2>${tx('ไอเดียต่อไปของคุณ','Your next project.')}</h2>${tx('ค้นหา Example แล้วต่อยอดจาก Source','Find an example. Make it yours.','p')}</div><a class="product-media hub-miniature" href="examples.html" aria-label="Browse the Developer Hub"><div class="mini-window" aria-hidden="true"><div class="mini-window-bar"><span></span><span></span><span></span><b>TESAIoT / PROJECT HUB</b></div><div class="mini-window-body"><span>WHAT WILL YOU BUILD?</span><div class="mini-categories"><i>CONTROL</i><i>SENSING</i><i>EDGE AI</i></div><div class="mini-projects"><div>${icon('sliders')}<span>INPUT → OUTPUT</span></div><div>${icon('sensor')}<span>SENSE → SEE</span></div><div>${icon('chip')}<span>EXPLORE AI</span></div></div><div class="mini-code">&lt;your next idea /&gt;</div></div></div></a><div class="product-tile-bottom"><p class="product-caption">EXAMPLES · SOURCE · LEARNING</p>${a('examples.html','เปิด Developer Hub','Open Developer Hub','button product-button')}</div></article>
 </section>
 <section class="section wrap home-featured">${sectionHead('MADE TO BE EXPLORED','เริ่มจากไอเดียที่มองเห็นผล','A little inspiration. A real starting point.','สามเรื่องที่คัดมาให้เริ่มรู้จักบอร์ด ก่อนเลือกโปรเจกต์ของคุณ','Three selected stories to meet the hardware and find your next project.')}${stories()}<div class="section-bottom">${a('featured.html','สำรวจ Featured Projects','Explore Featured Projects','button secondary')}</div></section>
 <section class="wrap next-path"><div><p class="eyebrow">YOUR NEXT STEP</p>${tx('จาก Example แรก สู่ Edge AI','From your first example to Edge AI.','h2')}${tx('เริ่มด้วย SDK ของ TESA แล้วสำรวจ Model และเครื่องมือ DEEPCRAFT ของ Infineon เมื่อพร้อม','Start with the TESA SDK. Explore Infineon’s DEEPCRAFT models and tools when you’re ready.','p')}</div><div class="actions">${a('learn.html','เริ่มต้น / Docs','Get started / Docs','button primary')}${a('edge-ai.html','สำรวจ Edge AI','Explore Edge AI','text-link')}</div></section>`;
}

export function resourcesPage() {
 const resource=(name,th,en,url)=>`<article><h2>${name}</h2>${tx(th,en,'p')}${a(url,'เปิดแหล่งข้อมูล','Open resource')}</article>`;
 return `<section class="wrap page-masthead"><p class="eyebrow">TESA / INFINEON / RESOURCES</p>${tx('เครื่องมือและเอกสาร สำหรับก้าวต่อไป','Resources for your next build.','h1')}${tx('ต้นทางที่เกี่ยวข้องกับบอร์ด ตัวอย่าง และแพลตฟอร์ม PSoC Edge E84','Direct resources for the boards, examples and PSoC Edge E84 platform.','p','class="lead"')}</section><section class="wrap resource-grid">
 ${resource('TESAIoT Dev Kit SDK','คู่มือบอร์ด SDK และข้อมูล Hardware ของ Training Kit','Training kit documentation, SDK and hardware information.','https://tesaiot.github.io/tesaiot-pse84-devkit-sdk/')}
 ${resource('TESAIoT Developer Hub','เปิดบริการ Developer Hub ของ TESA ที่ใช้งานอยู่','Open the existing TESA Developer Hub service.','https://dev.tesaiot.dev/')}
 ${resource('TESAIoT Example Sources','อ่าน Requirements และ Source Code ของตัวอย่าง','Read example requirements and source code.','https://github.com/tesaiot/developer-hub')}
 ${resource('PSoC™ Edge E84 AI Kit','ข้อมูล KIT_PSE84_AI จาก Infineon ตรวจอุปกรณ์และ Revision ของชุดที่ใช้','Official Infineon KIT_PSE84_AI information. Check your kit’s devices and revision.','https://www.infineon.com/product-information/kit_pse84_ai')}
 ${resource('DEEPCRAFT™','สำรวจ Model และเครื่องมือ Edge AI พร้อมตรวจ Target Support','Explore Edge AI models and tools; check target support.','https://deepcraft.infineon.com/')}
 ${resource('TESAIoT Platform','รู้จักแพลตฟอร์มและเส้นทางเรียนรู้เพิ่มเติมจาก TESA','Explore the TESA platform and further learning resources.','https://www.tesaiot.com/')}
 </section><section class="wrap section resource-notes"><details><summary>${tx('เครดิตสื่อและขอบเขต PoC','Media credits & PoC scope')}</summary>
 ${tx('ภาพและโมเดล Training มาจาก TESAIoT SDK · © TESA โมเดลไม่รวมโมดูล OPTIGA Trust M เสริมที่เห็นในภาพถ่าย อุปกรณ์จริงขึ้นกับชุดที่ใช้','Training image and 3D model: TESAIoT SDK · © TESA. The model does not include the optional OPTIGA Trust M module shown in the photograph. Actual accessories depend on the kit.','p')}
 ${tx('คลิป BENTO เป็น Demo เดิมที่ผู้ใช้ให้มา Hero ใช้ช่วง 9–25 วินาที ไม่มีเสียงหรือการเร่งเวลา ไม่ใช่ผลทดสอบใหม่หรือผลยืนยันบน NDR','BENTO is existing, user-supplied footage. The hero uses seconds 9–25, with no audio or speed change. It is not a new test or NDR validation.','p')}
 ${tx('NDR ใช้ภาพและโมเดล Concept รูปทรง ขนาด ตำแหน่งชิ้นส่วนและพอร์ตเป็นภาพจำลอง ไม่ใช่ CAD พร้อมผลิต ต้องยืนยัน Base Revision / BSP แยกจาก Training','NDR uses concept imagery and geometry. Shapes, sizes, component and port positions are illustrative, not manufacturing CAD. Confirm base revision and BSP separately from Training.','p')}
 ${tx('เว็บไซต์นี้เป็น Independent Design PoC ไม่มี Online Flash และไม่เชื่อมต่อ Hardware รายการ AI ของ Infineon เป็น Upstream Reference ยังไม่ใช่ผล Validation ของ TESA','This independent design PoC has no online flash or hardware connection. Infineon AI examples are upstream references, not TESA validation results.','p')}
 ${a('https://github.com/nitikorn20/tesaiot-board-explorer-poc/blob/main/THIRD_PARTY_NOTICES.md','เครดิตและสิทธิ์สื่อฉบับเต็ม','Full credits & media notices')}</details></section>`;
}
